"""One run of a parameter sweep, as a tool wrote it and not as a model typed it.

03/CP4 gave the guided agent a `module_results` channel holding **one** validated
configuration per module. A sweep needs *N* per module -- that is what a sweep is --
so the batch path needs a channel of its own, shaped the same way and written the
same way: by a tool, through `Command(update=...)`, never by the model.

The alternative is what the first-generation agent did. Its batch tool took

```python
run_specs: list[dict[str, Any]] | None = None,   # run_name + module_results
```

straight from the model (`agents/advanced_mode/tools.py:458`), so `advanced_mode`
reached execution through model-authored parameters -- reopening, for the batch path,
exactly what 03/CP1 and 03/CP4 close for the single-simulation path. **Closing it in
one agent and leaving it open in the other is worse than not closing it, because the
fix looks done.**

Two identifiers, and they are not the same identifier:

``run_name``
    Human-readable and **model-chosen**: "m=3 guide, 2 A" is a good name. It names a
    run in conversation and in a summary. It is not an identifier.

``simulation_run_id``
    A UUID generated by trusted application code, one per VITESS execution. It names
    the output directory. The first-generation batch tool passed `run_id=run_name`
    straight into the MCP call, so whatever the model called a run became a directory
    name on a shared volume.
"""

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, field_validator

from vitess_ai.schema.module_result import ModuleConfigurationResult

__all__ = ["MAX_SWEEP_RUNS", "SimulationPlanEntry"]

#: One limit shared by variant collection, matrix expansion and execution. A
#: module cannot contribute more variants than any valid sweep could consume.
#: 36 so a full 6 x 6 grid of two parameters fits.
MAX_SWEEP_RUNS = 36


class SimulationPlanEntry(BaseModel):
    """One simulation of a sweep: what it is called, where it goes, what it runs."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    run_name: str = Field(min_length=1, max_length=120)
    simulation_run_id: UUID
    #: One validated configuration per module, keyed by module name. The keys are
    #: checked against the catalog's execution order when the entry is executed, so
    #: a sweep cannot quietly run a four-module pipeline.
    modules: dict[str, ModuleConfigurationResult]

    @field_validator("run_name")
    @classmethod
    def clean_run_name(cls, value: str) -> str:
        cleaned = value.strip()
        if not cleaned:
            raise ValueError("run name must not be blank")
        if any(ord(character) < 32 or ord(character) == 127 for character in cleaned):
            raise ValueError("run name must not contain control characters")
        return cleaned
